apiVersion: eksctl.io/v1alpha5  
kind: ClusterConfig  
metadata:
  name: EKS-node-Cluster  
  region: ap-south-1  
vpc:
  id: vpc-0e3533c445af7b340   
  cidr: "192.168.0.0/16" # 
  subnets:  
    public:
      ap-south-1a:  
        id: subnet-0dbbb00629fb5b6c4
      ap-south-1b:
        id: subnet-045b5d05cc3bd2bc8
    private:
      ap-south-1a:
        id: subnet-040dc3b17111f0bad
      ap-south-1b:
        id: subnet-00d9ef52c437a11db

nodeGroups: 
  - name: EKS-public-workers 
    instanceType: t2.medium
    desiredCapacity: 2 
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true